-- Morfes Booking System — Supabase Setup
-- Run these in the Supabase SQL Editor (project dashboard → SQL Editor)

-- ─── 1. SERVICES ─────────────────────────────────────────────────────────────
create table if not exists services (
  id           bigint generated by default as identity primary key,
  emoji        text    default '✂️',
  name         text    not null,
  duration_min integer not null,
  active       boolean default true,
  created_at   timestamptz default now()
);

-- Seed default services
insert into services (emoji, name, duration_min, active) values
  ('✂️', 'Κούρεμα',                    45,  true),
  ('🎨', 'Βαφή & Ανταύγειες',          90,  true),
  ('💈', 'Barbershop (κούρεμα + ξύρισμα)', 60, true),
  ('💇', 'Styling & Blow-dry',          40,  true),
  ('💎', 'Face Spa & Θεραπείες',        60,  true)
on conflict do nothing;

-- ─── 2. WORKING HOURS ─────────────────────────────────────────────────────────
-- weekday: 0=Monday .. 6=Sunday  (matches (getDay()+6)%7 in JS)
create table if not exists working_hours (
  id         bigint generated by default as identity primary key,
  weekday    integer not null unique check (weekday between 0 and 6),
  is_open    boolean default true,
  open_time  time    default '09:00',
  close_time time    default '19:00'
);

-- Default: Mon–Sat open 09:00–19:00, Sunday closed
insert into working_hours (weekday, is_open, open_time, close_time) values
  (0, true,  '09:00', '19:00'),  -- Monday
  (1, true,  '09:00', '19:00'),  -- Tuesday
  (2, true,  '09:00', '19:00'),  -- Wednesday
  (3, true,  '09:00', '19:00'),  -- Thursday
  (4, true,  '09:00', '19:00'),  -- Friday
  (5, true,  '09:00', '19:00'),  -- Saturday
  (6, false, '09:00', '19:00')   -- Sunday (closed)
on conflict (weekday) do nothing;

-- ─── 3. BOOKING SETTINGS ──────────────────────────────────────────────────────
create table if not exists booking_settings (
  id        integer primary key default 1 check (id = 1),  -- singleton row
  slot_step integer default 30  -- minutes between available slots
);

insert into booking_settings (id, slot_step) values (1, 30)
on conflict (id) do nothing;

-- ─── 4. BLOCKED DATES ─────────────────────────────────────────────────────────
create table if not exists blocked_dates (
  id         bigint generated by default as identity primary key,
  date       date not null unique,
  created_at timestamptz default now()
);

-- ─── 5. BOOKINGS ──────────────────────────────────────────────────────────────
create table if not exists bookings (
  id             bigint generated by default as identity primary key,
  service_id     bigint references services(id) on delete set null,
  customer_name  text not null,
  customer_phone text not null,
  customer_email text,
  date           date not null,
  start_time     time not null,
  end_time       time not null,
  status         text not null default 'confirmed'
                   check (status in ('confirmed','cancelled')),
  created_at     timestamptz default now()
);

-- Index for availability checks
create index if not exists idx_bookings_date_status on bookings(date, status);

-- ─── 6. ROW LEVEL SECURITY ────────────────────────────────────────────────────
alter table services       enable row level security;
alter table working_hours  enable row level security;
alter table booking_settings enable row level security;
alter table blocked_dates  enable row level security;
alter table bookings       enable row level security;

-- Public anon can read services, working hours, settings, blocked dates
create policy "public read services"         on services         for select using (true);
create policy "public read working_hours"    on working_hours    for select using (true);
create policy "public read booking_settings" on booking_settings for select using (true);
create policy "public read blocked_dates"    on blocked_dates    for select using (true);
create policy "public read bookings"         on bookings         for select using (true);

-- Anon can insert bookings (customers booking)
create policy "public insert bookings"       on bookings         for insert with check (true);

-- Authenticated users (admins) can do everything
create policy "admin all services"           on services         for all using (auth.role() = 'authenticated');
create policy "admin all working_hours"      on working_hours    for all using (auth.role() = 'authenticated');
create policy "admin all booking_settings"   on booking_settings for all using (auth.role() = 'authenticated');
create policy "admin all blocked_dates"      on blocked_dates    for all using (auth.role() = 'authenticated');
create policy "admin all bookings"           on bookings         for all using (auth.role() = 'authenticated');

-- ─── 7. NOTES ─────────────────────────────────────────────────────────────────
-- After running this SQL:
-- 1. Create an admin user in Supabase Auth → Users → "Add user"
--    Use the email/password that will log into admin.html
-- 2. Copy your project URL and anon key from Settings → API
-- 3. Replace 'YOUR_SUPABASE_URL_HERE' and 'YOUR_SUPABASE_ANON_KEY_HERE'
--    in both booking.js and admin.js
-- 4. (Optional) Deploy the send-booking-email Edge Function for email confirmations
