-- ─── 1. Close Monday and Sunday ──────────────────────────────────────────────
update working_hours set is_open = false where weekday = 0; -- Monday
update working_hours set is_open = false where weekday = 6; -- Sunday

-- ─── 2. Create exception_dates table ─────────────────────────────────────────
-- Specific dates that override the weekly schedule
-- e.g. open a Monday, or close a Wednesday for a holiday
create table if not exists exception_dates (
  id         bigint generated by default as identity primary key,
  date       date not null unique,
  is_open    boolean not null default true,
  open_time  time,
  close_time time,
  note       text,
  created_at timestamptz default now()
);

-- ─── 3. RLS ───────────────────────────────────────────────────────────────────
alter table exception_dates enable row level security;

create policy "public read exception_dates"
  on exception_dates for select using (true);

create policy "admin all exception_dates"
  on exception_dates for all using (auth.role() = 'authenticated');
